# Generated by Django 4.0.5 on 2022-06-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_profile_company_alter_profile_position'),
        ('formsFandB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brands',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodities',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodities',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoditycategories',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoditycategories',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoditysubcategories',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoditysubcategories',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fagents',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fagents',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputs',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputs',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventories',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventories',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylist',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylist',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measuringunits',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measuringunits',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputs',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputs',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetypes',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurements',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurements',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttypes',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providers',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providers',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providertypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providertypes',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
    ]
