# Generated by Django 4.0.6 on 2022-07-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsFandB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputs',
            name='ProcurementID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formsFandB.procurements', verbose_name='ردیف خرید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylist',
            name='CommodityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commodities', verbose_name='ردیف قلم'),
        ),
        migrations.AddField(
            model_name='outputs',
            name='ProcurementID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formsFandB.procurements', verbose_name='ردیف خرید'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputs',
            name='CommodityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commodities', verbose_name='ردیف قلم'),
        ),
        migrations.AlterField(
            model_name='outputs',
            name='CommodityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commodities', verbose_name='ردیف قلم'),
        ),
    ]
