# Generated by Django 4.0.5 on 2022-06-19 18:03

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('formsFandB', '0002_rename_agents_fagents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventoryName', models.CharField(max_length=200, null=True, verbose_name='نام انبار')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategory', models.CharField(max_length=200, null=True, verbose_name='دسته\u200cبندی آیتم')),
                ('Unitprice', models.CharField(max_length=200, null=True, verbose_name='قیمت واحد')),
                ('ItemType', models.CharField(max_length=200, null=True, verbose_name='نوع آیتم')),
                ('Hour', models.CharField(max_length=200, null=True, verbose_name='ساعت')),
                ('OrderDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creator', models.CharField(max_length=200, null=True, verbose_name='ایجاد کننده')),
                ('RecipeName', models.CharField(max_length=200, null=True, verbose_name='نام دستور پخت')),
                ('LastVersionRecipeID', models.CharField(max_length=200, null=True, verbose_name='آیدی آخرین نسخه')),
                ('StartingYear', models.CharField(max_length=20, null=True, verbose_name='سال شروع')),
                ('Version', models.CharField(max_length=200, null=True, verbose_name='شماره نسخه')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('ProductTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.producttypes', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'دستور پخت',
                'verbose_name_plural': 'دستورهای پخت',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=200, null=True, verbose_name='نام غذا')),
                ('FoodPrice', models.FloatField(max_length=200, null=True, verbose_name='قیمت غذا')),
                ('Quantity', models.FloatField(null=True, verbose_name='مقدار')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('RecipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.recipes', verbose_name='دستور پخت')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(null=True, verbose_name='مقدار')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CommodityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commodities', verbose_name='قلم کالا')),
                ('MeasuringUnitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.measuringunits', verbose_name='واحد اندازه\u200cگیری')),
                ('RecipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.recipes', verbose_name='دستور پخت')),
            ],
            options={
                'verbose_name': 'جزئیات دستور پخت',
                'verbose_name_plural': 'جزئیات دستورهای پخت',
            },
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransferedDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ میلادی خروج')),
                ('TransferedDateJalali', django_jalali.db.models.jDateTimeField(max_length=200, null=True, verbose_name='تاریخ شمسی خروج')),
                ('TransferedQuantity', models.FloatField(null=True, verbose_name='مقدار')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('DeliveryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.fagents', verbose_name='مسئول تحویل')),
                ('FromInventoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.inventories', verbose_name='انبار')),
                ('ProcurementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.procurements', verbose_name='ردیف خرید')),
            ],
            options={
                'verbose_name': 'خروجی',
                'verbose_name_plural': 'خروجی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RemainingPackageCount', models.IntegerField(null=True, verbose_name='تعداد باقی\u200cمانده')),
                ('UpdateDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ به روز رسانی')),
                ('InventoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.inventories', verbose_name='انبار')),
                ('ProcurementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.procurements', verbose_name='ردیف خرید')),
            ],
            options={
                'verbose_name': 'اقلام انبار',
                'verbose_name_plural': 'لیست انبار',
            },
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransferedDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ میلادی خروج')),
                ('TransferedDateJalali', django_jalali.db.models.jDateTimeField(max_length=200, null=True, verbose_name='تاریخ شمسی خروج')),
                ('TransferedQuantity', models.FloatField(null=True, verbose_name='مقدار')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('ProcurementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.procurements', verbose_name='ردیف خرید')),
                ('ToInventoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.inventories', verbose_name='انبار')),
                ('TransfereeAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.fagents', verbose_name='مسئول تحویل')),
            ],
            options={
                'verbose_name': 'ورودی',
                'verbose_name_plural': 'ورودی\u200cها',
            },
        ),
    ]
