# Generated by Django 4.0.5 on 2022-06-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsFandB', '0003_inventories_orders_recipes_sales_recipeingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='BrandID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.brands', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='CommodityCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commoditycategories', verbose_name='دسته\u200cبندی اصلی قلم کالا'),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='CommoditySubCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commoditysubcategories', verbose_name='دسته\u200cبندی فرعی قلم کالا'),
        ),
        migrations.AlterField(
            model_name='commoditysubcategories',
            name='CommodityCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commoditycategories', verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='fagents',
            name='AgentRoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.roles', verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='procurements',
            name='CommodityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commodities', verbose_name='قلم کالا'),
        ),
        migrations.AlterField(
            model_name='procurements',
            name='MeasuringUnitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.measuringunits', verbose_name='واحد اندازه\u200cگیری'),
        ),
        migrations.AlterField(
            model_name='procurements',
            name='PackageTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.packagetypes', verbose_name='نوع بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='procurements',
            name='ProviderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.providers', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='ProviderTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsFandB.commoditycategories', verbose_name='نوع تامین کننده'),
        ),
    ]
