# Generated by Django 4.0.5 on 2022-06-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=200, null=True, verbose_name='نام برند')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommodityName', models.CharField(max_length=200, null=True, verbose_name='نام قلم کالا')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.brands', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'قلم کالا',
                'verbose_name_plural': 'لیست اقلام',
            },
        ),
        migrations.CreateModel(
            name='CommodityCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommodityCategory', models.CharField(max_length=200, null=True, verbose_name='دسته\u200cبندی اصلی اقلام')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اصلی اقلام',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اصلی اقلام',
            },
        ),
        migrations.CreateModel(
            name='MeasuringUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeasuringUnitTitle', models.CharField(max_length=200, null=True, verbose_name='واحد اندازه\u200cگیری')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'واحد اندازه\u200cگیری',
                'verbose_name_plural': 'واحدهای اندازه\u200cگیری',
            },
        ),
        migrations.CreateModel(
            name='PackageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageTypeTitle', models.CharField(max_length=200, null=True, verbose_name='نوع بسته\u200cبندی')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نوع بسته\u200cبندی',
                'verbose_name_plural': 'انواع بسته\u200cبندی',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductTypeTitle', models.CharField(max_length=200, null=True, verbose_name='نوع کالا')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نوع کالا',
                'verbose_name_plural': 'انواع کالا',
            },
        ),
        migrations.CreateModel(
            name='ProviderTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProviderTypeTitle', models.CharField(max_length=200, null=True, verbose_name='نوع تامین کننده')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نوع تامین کننده',
                'verbose_name_plural': 'انواع تامین کننده',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleTitle', models.CharField(max_length=200, null=True, verbose_name='نام نقش')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProviderName', models.CharField(max_length=200, null=True, verbose_name='نام تامین کننده')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('ProviderTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.commoditycategories', verbose_name='نوع تامین کننده')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Procurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitPrice', models.FloatField(null=True, verbose_name='قیمت واحد')),
                ('Price', models.FloatField(null=True, verbose_name='قیمت')),
                ('PackageCount', models.IntegerField(null=True, verbose_name='تعداد')),
                ('PackageUnitValue', models.FloatField(null=True, verbose_name='مقدار در بسته\u200cبندی')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CommodityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.commodities', verbose_name='قلم کالا')),
                ('MeasuringUnitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.measuringunits', verbose_name='واحد اندازه\u200cگیری')),
                ('PackageTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.packagetypes', verbose_name='نوع بسته\u200cبندی')),
                ('ProviderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.providers', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'لیست خرید',
            },
        ),
        migrations.CreateModel(
            name='CommoditySubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommoditySubCategory', models.CharField(max_length=200, null=True, verbose_name='دسته\u200cبندی فرعی اقلام')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CommodityCatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.commoditycategories', verbose_name='دسته\u200cبندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی فرعی اقلام',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای فرعی اقلام',
            },
        ),
        migrations.AddField(
            model_name='commodities',
            name='CommodityCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.commoditycategories', verbose_name='دسته\u200cبندی اصلی قلم کالا'),
        ),
        migrations.AddField(
            model_name='commodities',
            name='CommoditySubCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.commoditysubcategories', verbose_name='دسته\u200cبندی فرعی قلم کالا'),
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentFirstName', models.CharField(max_length=200, null=True, verbose_name='نام مسئول')),
                ('AgentLastName', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی مسئول')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('AgentRoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsinput.roles', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'مسئول',
                'verbose_name_plural': 'مسئول\u200cها',
            },
        ),
    ]
