# Generated by Django 4.0.5 on 2022-06-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsinput', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='FAgents',
        ),
    ]
