# Generated by Django 4.0.5 on 2022-06-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='ip_address',
        ),
    ]
