# Generated by Django 4.0.5 on 2022-06-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_remove_profile_industry'),
        ('ticketing', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='سازنده تیکت'),
            preserve_default=False,
        ),
    ]
