# Generated by Django 4.0.5 on 2022-06-19 12:41

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(max_length=10, null=True, verbose_name='شماره قرارداد')),
                ('CustomerName', models.CharField(max_length=200, null=True, verbose_name='نام مشتری')),
                ('PrePayment', models.FloatField(max_length=200, null=True, verbose_name='مبلغ پیش پرداخت')),
                ('ContractPrice', models.FloatField(max_length=200, null=True, verbose_name='مبلغ کل قرارداد')),
                ('ContractConfirmDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی ثبت قرارداد')),
                ('ContractConfirmDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی ثبت قرارداد')),
                ('IsCancelled', models.BooleanField(max_length=5, null=True, verbose_name='فسخ شده')),
                ('IsExpanded', models.BooleanField(max_length=5, null=True, verbose_name='تمدید شده')),
                ('ValueAddedTax', models.BooleanField(max_length=5, null=True, verbose_name='مالیات بر ارزش افزوده')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('AgentNameID', models.IntegerField(max_length=3, null=True, verbose_name='مسئول فروش')),
                ('CancelingDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی فسخ')),
                ('CancelingDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی فسخ')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
    ]
