# Generated by Django 4.0.5 on 2022-06-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsscontract', '0003_alter_agents_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200, null=True, verbose_name='نام مشتری')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='CustomerName',
        ),
        migrations.AddField(
            model_name='contracts',
            name='CustomerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formsscontract.customers', verbose_name='آیدی مشتری'),
            preserve_default=False,
        ),
    ]
