# Generated by Django 4.0.5 on 2022-06-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsscontract', '0004_customers_remove_contracts_customername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IranProvinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinceName', models.CharField(max_length=200, null=True, verbose_name='نام منطقه')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'مناطق',
            },
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='ContractID',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='AgentNameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsscontract.agents', verbose_name='مسئول فروش'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsscontract.customers', verbose_name='مشتری'),
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=200, null=True, verbose_name='نام شهر')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('ProvinceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsscontract.iranprovinces', verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
    ]
