# Generated by Django 4.0.5 on 2022-06-19 14:57

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('formsscontract', '0009_salespackages_packagedetailsperboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerPaymentMethodName', models.CharField(max_length=200, null=True, verbose_name='نام روش پرداخت')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installment', models.FloatField(null=True, verbose_name='مبلغ قسط')),
                ('InstallmentNumber', models.IntegerField(null=True, verbose_name='نوبت قسط')),
                ('PaymentDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی پرداخت')),
                ('PaymentDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی پرداخت')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsscontract.contracts', verbose_name='قرارداد')),
                ('CustomerPaymentMethodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsscontract.customerpaymentmethod', verbose_name='روش پرداخت')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
            },
        ),
    ]
