# Generated by Django 4.0.5 on 2022-07-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='../apps/media/blogimages', verbose_name='تصویر'),
        ),
    ]
