# Generated by Django 4.0.5 on 2022-06-29 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('logo', models.ImageField(default='profileimages/profi.png', null=True, upload_to='companyimages', verbose_name='لوگو')),
                ('sphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت')),
                ('mphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(blank=True, default='c', max_length=1, null=True, verbose_name='نقش')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='c', max_length=1, null=True, verbose_name='رده')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='نام\u200cخانوادگی')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('pic', models.ImageField(default='profileimages/profi.png', null=True, upload_to='profileimages', verbose_name='تصویر')),
                ('sphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت')),
                ('mphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت حساب')),
                ('Industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='useraccount.industry', verbose_name='صنعت')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='useraccount.company', verbose_name='شرکت')),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='useraccount.position', verbose_name='رده')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب\u200cهای کاربری',
            },
        ),
    ]
