# Generated by Django 4.0.5 on 2022-06-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='Role',
        ),
        migrations.AddField(
            model_name='industry',
            name='Industry',
            field=models.CharField(blank=True, default='c', max_length=40, null=True, verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(blank=True, default='c', max_length=40, null=True, verbose_name='رده'),
        ),
    ]
