# Generated by Django 4.0.5 on 2022-06-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_remove_industry_role_industry_industry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': 'صنایع'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'رده', 'verbose_name_plural': 'رده\u200cها'},
        ),
    ]
