# Generated by Django 4.0.5 on 2022-06-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_remove_company_logo_remove_company_mphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Industry',
        ),
    ]
