# Generated by Django 4.0.5 on 2022-06-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_profile_company_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IndustrySel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.industry', verbose_name='صنعت'),
        ),
    ]
