# Generated by Django 4.0.5 on 2022-06-29 07:39

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentFirstName', models.CharField(max_length=200, null=True, verbose_name='نام مسئول فروش')),
                ('AgentLastName', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی مسئول فروش')),
                ('PositionID', models.IntegerField(null=True, verbose_name='آیدی سطح')),
                ('AgentCode', models.IntegerField(null=True, verbose_name='کد مسئول')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'مسئول',
                'verbose_name_plural': 'مسئول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardCode', models.CharField(max_length=200, null=True, verbose_name='کد تابلو')),
                ('BoardScore', models.CharField(max_length=20, null=True, verbose_name='امتیاز تابلو')),
                ('BoardDescription', models.CharField(max_length=200, null=True, verbose_name='توضیحات تابلو')),
                ('Dimenstions', models.CharField(max_length=20, null=True, verbose_name='ابعاد')),
                ('PlacementComments', models.CharField(max_length=200, null=True, verbose_name='نظرات')),
                ('Area', models.CharField(max_length=20, null=True, verbose_name='ناحیه')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'تابلو',
                'verbose_name_plural': 'تابلوها',
            },
        ),
        migrations.CreateModel(
            name='BoardTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardType', models.CharField(max_length=200, null=True, verbose_name='نوع تابلو')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نوع تابلو',
                'verbose_name_plural': 'انواع تابلو',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=200, null=True, verbose_name='نام شهر')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره قرارداد')),
                ('PrePayment', models.FloatField(blank=True, null=True, verbose_name='مبلغ پیش پرداخت')),
                ('ContractPrice', models.FloatField(blank=True, max_length=200, null=True, verbose_name='مبلغ کل قرارداد')),
                ('ContractConfirmDate', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاریخ میلادی ثبت قرارداد')),
                ('ContractConfirmDateJalali', django_jalali.db.models.jDateField(blank=True, max_length=200, null=True, verbose_name='تاریخ شمسی ثبت قرارداد')),
                ('IsCancelled', models.BooleanField(default=False, verbose_name='فسخ شده')),
                ('IsExpanded', models.BooleanField(default=False, verbose_name='تمدید شده')),
                ('ValueAddedTax', models.BooleanField(default=False, verbose_name='مالیات بر ارزش افزوده')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CancelingDate', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاریخ میلادی فسخ')),
                ('CancelingDateJalali', django_jalali.db.models.jDateField(blank=True, max_length=200, null=True, verbose_name='تاریخ شمسی فسخ')),
                ('AgentNameID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agents', verbose_name='مسئول فروش')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerPaymentMethodName', models.CharField(max_length=200, null=True, verbose_name='نام روش پرداخت')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200, null=True, verbose_name='نام مشتری')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='IranProvinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinceName', models.CharField(max_length=200, null=True, verbose_name='نام منطقه')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'مناطق',
            },
        ),
        migrations.CreateModel(
            name='SalesPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageName', models.CharField(max_length=200, null=True, verbose_name='نام پکیج فروش')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('AgentNameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agents', verbose_name='مسئول فروش')),
            ],
            options={
                'verbose_name': 'پکیج فروش',
                'verbose_name_plural': 'پکیج\u200cهای فروش',
            },
        ),
        migrations.CreateModel(
            name='PackageDetailsPerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('DeactivationDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی غیرفعال شدن')),
                ('DeactivationDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی غیرفعال شدن')),
                ('ActivationDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی فعال شدن')),
                ('ActivationDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی فعال شدن')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('BoardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.boards', verbose_name='تابلو')),
                ('PackageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.salespackages', verbose_name='پکیج فروش')),
            ],
            options={
                'verbose_name': 'تابلو در پکیج',
                'verbose_name_plural': 'تابلوها در پکیج\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=200, null=True, verbose_name='نام جایگاه')),
                ('LocationCode', models.CharField(max_length=200, null=True, verbose_name='کد جایگاه')),
                ('LocationTypeID', models.CharField(max_length=200, null=True, verbose_name='کد نوع جایگاه')),
                ('Longitude', models.FloatField(null=True, verbose_name='طول جغرافیایی')),
                ('Latitude', models.FloatField(null=True, verbose_name='عرض جغرافیایی')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.cities', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'جایگاه',
                'verbose_name_plural': 'جایگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installment', models.FloatField(blank=True, null=True, verbose_name='مبلغ قسط')),
                ('InstallmentNumber', models.IntegerField(blank=True, null=True, verbose_name='نوبت قسط')),
                ('PaymentDate', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاریخ میلادی پرداخت')),
                ('PaymentDateJalali', django_jalali.db.models.jDateField(blank=True, max_length=200, null=True, verbose_name='تاریخ شمسی پرداخت')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('ContractID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.contracts', verbose_name='قرارداد')),
                ('CustomerPaymentMethodID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.customerpaymentmethod', verbose_name='روش پرداخت')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.customers', verbose_name='مشتری'),
        ),
        migrations.CreateModel(
            name='ContractDetailsPerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardContractPrice', models.FloatField(blank=True, null=True, verbose_name='مبلغ قرارداد تابلو')),
                ('DailyPrice', models.FloatField(blank=True, max_length=200, null=True, verbose_name='مبلغ روزشمار تابلو در قرارداد')),
                ('ContractStart', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاریخ میلادی شروع اکران')),
                ('JalaliStart', django_jalali.db.models.jDateField(blank=True, max_length=200, null=True, verbose_name='تاریخ شمسی شروع اکران')),
                ('ContractFinish', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاریخ میلادی پایان اکران')),
                ('JalaliFinish', django_jalali.db.models.jDateField(blank=True, max_length=200, null=True, verbose_name='تاریخ شمسی پایان اکران')),
                ('ContractYearBase', models.CharField(blank=True, max_length=200, null=True, verbose_name='سال پایه قرارداد')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('AgentNameID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agents', verbose_name='مسئول فروش')),
                ('BoardID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.boards', verbose_name='تابلو')),
                ('ContractID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.contracts', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'تابلو در قرارداد',
                'verbose_name_plural': 'تابلوها در قراردادها',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='ProvinceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.iranprovinces', verbose_name='منطقه'),
        ),
        migrations.AddField(
            model_name='boards',
            name='BoardTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.boardtypes', verbose_name='نوع تابلو'),
        ),
        migrations.AddField(
            model_name='boards',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.locations', verbose_name='جایگاه'),
        ),
    ]
