# Generated by Django 4.0.5 on 2022-06-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentPaymentMethodName', models.CharField(max_length=200, null=True, verbose_name='نام روش پرداخت')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'روش پرداخت به مسئول',
                'verbose_name_plural': 'روش\u200cهای پرداخت به مسئولان',
            },
        ),
        migrations.AddField(
            model_name='agents',
            name='AgentMail',
            field=models.CharField(max_length=200, null=True, verbose_name='ایمیل مسئول'),
        ),
        migrations.AddField(
            model_name='agents',
            name='AgentPhone',
            field=models.CharField(max_length=200, null=True, verbose_name='شماره تلفن مسئول'),
        ),
        migrations.AddField(
            model_name='agents',
            name='AgentPaymentMethodID',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agentpaymentmethods', verbose_name='روش پرداخت به مسئول'),
            preserve_default=False,
        ),
    ]
