# Generated by Django 4.0.5 on 2022-06-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentFirstName', models.CharField(max_length=200, null=True, verbose_name='نام مسئول فروش')),
                ('AgentLastName', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی مسئول فروش')),
                ('PositionID', models.IntegerField(null=True, verbose_name='آیدی سطح')),
                ('AgentCode', models.IntegerField(null=True, verbose_name='کد مسئول')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='ContractID',
            field=models.IntegerField(null=True, verbose_name='آیدی قرارداد'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='AgentNameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agents', verbose_name='آیدی مسئول فروش'),
        ),
    ]
