# Generated by Django 4.0.6 on 2022-07-11 18:18

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
        ('formsOOH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBoards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardCode', models.CharField(max_length=200, null=True, verbose_name='کد تابلو')),
                ('Area', models.CharField(max_length=20, null=True, verbose_name='ناحیه')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'تابلو عملیات',
                'verbose_name_plural': 'تابلوهای عملیات',
            },
        ),
        migrations.CreateModel(
            name='OContractDetailsPerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('BoardID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.oboards', verbose_name='تابلو')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'تابلو در قرارداد عملیات',
                'verbose_name_plural': 'تابلوها در قراردادهای عملیات',
            },
        ),
        migrations.CreateModel(
            name='OContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contractor', models.CharField(max_length=200, null=True, verbose_name='پیمانکار')),
                ('ContractorType', models.CharField(max_length=200, null=True, verbose_name='نوع پیمانکار')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'پیمانکار',
                'verbose_name_plural': 'پیمانکاران',
            },
        ),
        migrations.CreateModel(
            name='OTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TariffActivationDate', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ فعال سازی تعرفه')),
                ('TariffDeactivationDate', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ غیر فعال سازی تعرفه')),
                ('SideNumber', models.IntegerField(null=True, verbose_name='شماره وجه')),
                ('TariffParameter', models.IntegerField(null=True, verbose_name='پارامتر تعرفه')),
                ('TariffFee', models.FloatField(blank=True, null=True, verbose_name='مبلغ تعرفه')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.cities', verbose_name='شهر')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'تعرفه عملیات',
                'verbose_name_plural': 'تعرفه\u200cهای عملیات',
            },
        ),
        migrations.CreateModel(
            name='OOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationType', models.CharField(max_length=200, null=True, verbose_name='نوع عملیات')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'نوع عملیات',
                'verbose_name_plural': 'انواع عملیات',
            },
        ),
        migrations.CreateModel(
            name='OOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationDate', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ عملیات')),
                ('OperationDateJalali', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ شمسی عملیات')),
                ('OperationFee', models.FloatField(blank=True, null=True, verbose_name='فی')),
                ('OperationTariff', models.FloatField(blank=True, null=True, verbose_name='تعرفه')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('ContractDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.ocontractdetailsperboard', verbose_name='تابلو در قرارداد')),
                ('ContractorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.ocontractor', verbose_name='پیمانکار')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
                ('OperationTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.ooperationtype', verbose_name='نوع عملیات')),
            ],
            options={
                'verbose_name': 'عملیات',
                'verbose_name_plural': 'عملیات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=200, null=True, verbose_name='نام جایگاه')),
                ('LocationCode', models.CharField(max_length=200, null=True, verbose_name='کد جایگاه')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.cities', verbose_name='شهر')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
                ('LocationTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.locationtypes', verbose_name='نوع جایگاه')),
            ],
            options={
                'verbose_name': 'جایگاه عملیات',
                'verbose_name_plural': 'جایگاه\u200cهای عملیات',
            },
        ),
        migrations.CreateModel(
            name='OCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200, null=True, unique=True, verbose_name='نام مشتری عملیات')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'مشتری عملیات',
                'verbose_name_plural': 'مشتریان عملیات',
            },
        ),
        migrations.CreateModel(
            name='OContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره قرارداد')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.ocustomers', verbose_name='مشتری')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'قرارداد عملیات',
                'verbose_name_plural': 'قراردادهای عملیات',
            },
        ),
        migrations.CreateModel(
            name='OContractorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentFee', models.FloatField(blank=True, null=True, verbose_name='فی')),
                ('PaymentDate', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت')),
                ('PaymentDateJalali', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ شمسی پرداخت')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('ContractorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.ocontractor', verbose_name='آیدی پیمانکار')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'پرداخت به پیمانکار',
                'verbose_name_plural': 'پرداختی\u200cهای پیمانکاران',
            },
        ),
        migrations.AddField(
            model_name='ocontractdetailsperboard',
            name='ContractID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.ocontracts', verbose_name='قرارداد'),
        ),
        migrations.AddField(
            model_name='ocontractdetailsperboard',
            name='EntryAgent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
        ),
        migrations.CreateModel(
            name='OBoardTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardType', models.CharField(max_length=200, null=True, verbose_name='نوع تابلو')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت')),
                ('EntryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'نوع تابلو عملیات',
                'verbose_name_plural': 'انواع تابلو عملیات',
            },
        ),
        migrations.AddField(
            model_name='oboards',
            name='BoardTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.oboardtypes', verbose_name='نوع تابلو'),
        ),
        migrations.AddField(
            model_name='oboards',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='oboards',
            name='EntryAgent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='oboards',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.olocations', verbose_name='جایگاه'),
        ),
    ]
