# Generated by Django 4.0.6 on 2022-07-11 19:13

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0002_oboards_ocontractdetailsperboard_ocontractor_otariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocontracts',
            name='ContractConfirmDate',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='تاریخ میلادی ثبت قرارداد'),
        ),
        migrations.AddField(
            model_name='ocontracts',
            name='ContractConfirmDateJalali',
            field=django_jalali.db.models.jDateField(blank=True, max_length=200, null=True, verbose_name='تاریخ شمسی ثبت قرارداد'),
        ),
        migrations.AlterField(
            model_name='ocontractorpayment',
            name='PaymentDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='ocontractorpayment',
            name='PaymentDateJalali',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شمسی پرداخت'),
        ),
        migrations.AlterField(
            model_name='ooperation',
            name='OperationDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ عملیات'),
        ),
        migrations.AlterField(
            model_name='ooperation',
            name='OperationDateJalali',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شمسی عملیات'),
        ),
        migrations.AlterField(
            model_name='otariff',
            name='TariffActivationDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فعال سازی تعرفه'),
        ),
        migrations.AlterField(
            model_name='otariff',
            name='TariffDeactivationDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ غیر فعال سازی تعرفه'),
        ),
    ]
