# Generated by Django 4.0.5 on 2022-06-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0002_agents_contracts_contractid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name': 'مسئول', 'verbose_name_plural': 'مسئول\u200cها'},
        ),
    ]
