# Generated by Django 4.0.5 on 2022-06-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0003_alter_boards_dimenstions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationTypeName', models.CharField(max_length=200, null=True, verbose_name='نوع جایگاه')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نوع جایگاه',
                'verbose_name_plural': 'انواع جایگاه',
            },
        ),
        migrations.AlterField(
            model_name='locations',
            name='LocationTypeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formsOOH.locationtypes', verbose_name='نوع جایگاه'),
            preserve_default=False,
        ),
    ]
