# Generated by Django 4.0.5 on 2022-06-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_remove_profile_industry'),
        ('formsOOH', '0004_locationtypes_alter_locations_locationtypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='iranprovinces',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iranprovinces',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
    ]
