# Generated by Django 4.0.5 on 2022-06-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0005_iranprovinces_remove_contracts_contractid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardType', models.CharField(max_length=200, null=True, verbose_name='نوع تابلو')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
            ],
            options={
                'verbose_name': 'نوع تابلو',
                'verbose_name_plural': 'انواع تابلو',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=200, null=True, verbose_name='نام جایگاه')),
                ('LocationCode', models.CharField(max_length=200, null=True, verbose_name='کد جایگاه')),
                ('LocationTypeID', models.CharField(max_length=200, null=True, verbose_name='کد نوع جایگاه')),
                ('Longitude', models.FloatField(null=True, verbose_name='طول جغرافیایی')),
                ('Latitude', models.FloatField(null=True, verbose_name='عرض جغرافیایی')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.cities', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'جایگاه',
                'verbose_name_plural': 'جایگاه\u200cها',
            },
        ),
    ]
