# Generated by Django 4.0.5 on 2022-06-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_remove_profile_industry'),
        ('formsOOH', '0005_iranprovinces_company_iranprovinces_entryagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranprovinces',
            name='EntryAgent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='useraccount.profile', verbose_name='ثبت کننده'),
        ),
    ]
