# Generated by Django 4.0.5 on 2022-06-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_profile_company_alter_profile_position'),
        ('formsOOH', '0006_alter_iranprovinces_entryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpaymentmethods',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentpaymentmethods',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boards',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boards',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardtypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardtypes',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractdetailsperboard',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractdetailsperboard',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracts',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracts',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedetailsperboard',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedetailsperboard',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salespackages',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salespackages',
            name='EntryAgent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iranprovinces',
            name='EntryAgent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.profile', verbose_name='ثبت کننده'),
        ),
    ]
