# Generated by Django 4.0.5 on 2022-06-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0006_boardtypes_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardCode', models.CharField(max_length=200, null=True, verbose_name='کد تابلو')),
                ('BoardScore', models.CharField(max_length=20, null=True, verbose_name='امتیاز تابلو')),
                ('BoardDescription', models.CharField(max_length=200, null=True, verbose_name='توضیحات تابلو')),
                ('Dimenstions', models.CharField(max_length=20, null=True, verbose_name='ابعاد')),
                ('PlacementComments', models.CharField(max_length=200, null=True, verbose_name='نظرات')),
                ('Area', models.CharField(max_length=20, null=True, verbose_name='ناحیه')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('BoardTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.boardtypes', verbose_name='نوع تابلو')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.locations', verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'تابلو',
                'verbose_name_plural': 'تابلوها',
            },
        ),
    ]
