# Generated by Django 4.0.5 on 2022-06-19 14:28

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0007_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='PrePayment',
            field=models.FloatField(null=True, verbose_name='مبلغ پیش پرداخت'),
        ),
        migrations.CreateModel(
            name='ContractDetailsPerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardContractPrice', models.FloatField(null=True, verbose_name='مبلغ قرارداد تابلو')),
                ('DailyPrice', models.FloatField(max_length=200, null=True, verbose_name='مبلغ روزشمار تابلو در قرارداد')),
                ('ContractStart', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی شروع اکران')),
                ('JalaliStart', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی شروع اکران')),
                ('ContractFinish', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی پایان اکران')),
                ('JalaliFinish', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی پایان اکران')),
                ('ContractYearBase', models.CharField(max_length=200, null=True, verbose_name='سال پایه قرارداد')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('AgentNameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agents', verbose_name='مسئول فروش')),
                ('BoardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.boards', verbose_name='تابلو')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.contracts', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'تابلو در قرارداد',
                'verbose_name_plural': 'تابلوها در قراردادها',
            },
        ),
    ]
