# Generated by Django 4.0.5 on 2022-07-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0007_agentpaymentmethods_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='CustomerName',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='نام مشتری'),
        ),
    ]
