# Generated by Django 4.0.5 on 2022-06-19 14:48

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('formsOOH', '0008_alter_contracts_prepayment_contractdetailsperboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageName', models.CharField(max_length=200, null=True, verbose_name='نام پکیج فروش')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('AgentNameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.agents', verbose_name='مسئول فروش')),
            ],
            options={
                'verbose_name': 'پکیج فروش',
                'verbose_name_plural': 'پکیج\u200cهای فروش',
            },
        ),
        migrations.CreateModel(
            name='PackageDetailsPerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityStatus', models.BooleanField(max_length=5, null=True, verbose_name='فعال/غیرفعال')),
                ('DeactivationDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی غیرفعال شدن')),
                ('DeactivationDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی غیرفعال شدن')),
                ('ActivationDate', models.DateField(max_length=200, null=True, verbose_name='تاریخ میلادی فعال شدن')),
                ('ActivationDateJalali', django_jalali.db.models.jDateField(max_length=200, null=True, verbose_name='تاریخ شمسی فعال شدن')),
                ('EntryDate', models.DateTimeField(max_length=200, null=True, verbose_name='تاریخ ثبت رکورد')),
                ('BoardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.boards', verbose_name='تابلو')),
                ('PackageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsOOH.salespackages', verbose_name='پکیج فروش')),
            ],
            options={
                'verbose_name': 'تابلو در پکیج',
                'verbose_name_plural': 'تابلوها در پکیج\u200cها',
            },
        ),
    ]
